### ISSUE TITLE
error: 'sqrtf' was not declared in this scope

### ISSUE THREAD

**Issue by peterwilli** [ARMmbed/mbed-js-example#12]
Hi there,

I'm trying to do `sudo gulp --target=NRF51_DK` on a fresh copy of this repo. I installed gulp and the mbed cli. The following error appears. 

My Ubuntu version is 16.04 with Node v6.11.2.
Kernel is: `4.10.0-32-generic`

I installed the following packages to start build: gcc-arm-none-eabi (from original repo)
MBed CLI version is: 1.2.0

```
➜  mbed-js-example git:(master) sudo gulp --target=NRF51_DK
[15:38:11] Using gulpfile ~/Projects/flashIO/js-test/mbed-js-example/Gulpfile.js
[15:38:11] Starting 'make-build-dir'...
[15:38:11] Finished 'make-build-dir' after 353 μs
[15:38:11] Starting 'makefile'...
[15:38:11] Starting 'bundle'...
[15:38:11] Starting 'ignorefile'...
[15:38:11] Finished 'makefile' after 77 ms
[15:38:11] Starting 'get-jerryscript'...
[15:38:11] Finished 'ignorefile' after 57 ms
[15:38:11] Finished 'bundle' after 220 ms
$ git clone https://github.com/jerryscript-project/jerryscript; cd jerryscript; git checkout 82a94d0f883399ae7910ba03ae9b1b1bb87459c4; cd ..; pip install -r jerryscript/targets/mbedos5/tools/requirements.txt
Cloning into 'jerryscript'...
Note: checking out '82a94d0f883399ae7910ba03ae9b1b1bb87459c4'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 82a94d0... target: mbedos5: Update to mbed OS 5.5.5 (#1982)
The directory '/home/peter/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/peter/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: pycparser<=2.17 in /usr/local/lib/python2.7/dist-packages (from -r jerryscript/targets/mbedos5/tools/requirements.txt (line 1))
Requirement already satisfied: simpleeval in /usr/local/lib/python2.7/dist-packages (from -r jerryscript/targets/mbedos5/tools/requirements.txt (line 2))
Requirement already satisfied: pycparserext in /usr/local/lib/python2.7/dist-packages (from -r jerryscript/targets/mbedos5/tools/requirements.txt (line 3))
Requirement already satisfied: ply>=3.4 in /usr/local/lib/python2.7/dist-packages (from pycparserext->-r jerryscript/targets/mbedos5/tools/requirements.txt (line 3))
[15:38:44] Finished 'get-jerryscript' after 33 s
[15:38:44] Starting 'getlibs'...
[15:41:54] Finished 'getlibs' after 3.15 min
[15:41:54] Starting 'cppify'...
$ make getlibs
[mbed] ERROR: Could not find mbed program in current path "/home/peter/Projects/flashIO/js-test/mbed-js-example/build/jerryscript/targets/mbedos5".
[mbed] ERROR: Change the current directory to a valid mbed program, set the current directory as an mbed program with 'mbed config root .', or use the '--global' option to set global configuration.
---
echo 'ROOT=.' > .mbed
mbed config root .
[mbed] . now set as default root in program "mbedos5"
mbed toolchain GCC_ARM
[mbed] GCC_ARM now set as default toolchain in program "mbedos5"
mbed target 
[mbed] No default target set in program "mbedos5"
mbed deploy
[mbed] WARNING: Program "mbedos5" in "/home/peter/Projects/flashIO/js-test/mbed-js-example/build/jerryscript/targets/mbedos5" does not use source control management.
[mbed] WARNING: To fix this you should use "mbed new ." in the root of your program.
---
[mbed] Adding library "mbed-os" from "https://github.com/ARMmbed/mbed-os" at rev #db4be94693c3
[15:41:54] Finished 'cppify' after 84 ms
[15:41:54] Starting 'build'...
[15:41:57] Found no native packages.
$ make BOARD=NRF51_DK EXTRAS=
[15:41:57] build/make
[15:41:57] Finished 'build' after 3 s
[15:41:57] Starting 'default'...
[15:41:57] Finished 'default' after 8.5 μs
cd jerryscript/targets/mbedos5 && pip install -r tools/requirements.txt && rm -f source/js_encoded.cpp && rm -f source/pins.cpp && rm -f source/main.cpp && make BOARD=NRF51_DK EXTRA_SRC="../../../source" EXTERN_BUILD_DIR=../../../out/NRF51_DK NO_JS=1
The directory '/home/peter/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/peter/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: pycparser<=2.17 in /usr/local/lib/python2.7/dist-packages (from -r tools/requirements.txt (line 1))
Requirement already satisfied: simpleeval in /usr/local/lib/python2.7/dist-packages (from -r tools/requirements.txt (line 2))
Requirement already satisfied: pycparserext in /usr/local/lib/python2.7/dist-packages (from -r tools/requirements.txt (line 3))
Requirement already satisfied: ply>=3.4 in /usr/local/lib/python2.7/dist-packages (from pycparserext->-r tools/requirements.txt (line 3))
make[1]: Entering directory '/home/peter/Projects/flashIO/js-test/mbed-js-example/build/jerryscript/targets/mbedos5'
python tools/generate_pins.py NRF51_DK
cp ./template-mbedignore.txt ../../.mbedignore
mbed target NRF51_DK
[mbed] NRF51_DK now set as default target in program "mbedos5"
mbed compile -j0 --source . --source ../../ --source ../../../source --build ../../../out/NRF51_DK -D "CONFIG_MEM_HEAP_AREA_SIZE=(1024*16)" -t GCC_ARM
Building project mbedos5 (NRF51_DK, GCC_ARM)
Scan: .
Scan: 
Scan: source
Scan: mbed
Scan: env
Scan: FEATURE_BLE
Compile [  0.2%]: jerry-debugger.c
Compile [  0.4%]: jerry-snapshot.c
Compile [  0.7%]: debugger-sha1.c
Compile [  0.9%]: debugger-ws.c
Compile [  1.1%]: debugger.c
Compile [  1.3%]: ecma-alloc.c
Compile [  1.5%]: jerry.c
Compile [  1.7%]: ecma-gc.c
Compile [  2.0%]: ecma-helpers-external-pointers.c
Compile [  2.2%]: ecma-helpers-errol.c
Compile [  2.4%]: ecma-helpers-conversion.c
Compile [  2.6%]: ecma-helpers-number.c
Compile [  2.8%]: ecma-helpers-value.c
Compile [  3.0%]: ecma-helpers-values-collection.c
Compile [  3.3%]: ecma-helpers-string.c
Compile [  3.5%]: main.cpp
[Error] arm_math.h@5842,23: 'sqrtf' was not declared in this scope
[ERROR] In file included from ./mbed-os/rtos/rtx5/TARGET_CORTEX_M/core_cm.h:34:0,
                 from ./mbed-os/rtos/rtx5/TARGET_CORTEX_M/rtx_lib.h:33,
                 from ./mbed-os/rtos/mbed_rtos_storage.h:43,
                 from ./mbed-os/rtos/rtos.h:30,
                 from ./mbed-os/mbed.h:38,
                 from ../../../source/main.cpp:3:
./mbed-os/cmsis/arm_math.h: In function 'arm_status arm_sqrt_f32(float32_t, float32_t*)':
./mbed-os/cmsis/arm_math.h:5842:23: error: 'sqrtf' was not declared in this scope
       *pOut = sqrtf(in);
                       ^

[mbed] ERROR: "/usr/bin/python" returned error code 1.
[mbed] ERROR: Command "/usr/bin/python -u /home/peter/Projects/flashIO/js-test/mbed-js-example/build/jerryscript/targets/mbedos5/mbed-os/tools/make.py -t GCC_ARM -m NRF51_DK --source . --source ../../ --source ../../../source --build ../../../out/NRF51_DK -j0 -D CONFIG_MEM_HEAP_AREA_SIZE=(1024*16)" in "/home/peter/Projects/flashIO/js-test/mbed-js-example/build/jerryscript/targets/mbedos5"
---
Makefile:56: recipe for target 'all' failed
make[1]: Leaving directory '/home/peter/Projects/flashIO/js-test/mbed-js-example/build/jerryscript/targets/mbedos5'
make[1]: *** [all] Error 1
make: *** [all] Error 2
Makefile:14: recipe for target 'all' failed
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Command `make BOARD=NRF51_DK EXTRAS=` exited with code 2
    at ChildProcess.handleSubShellExit (/home/peter/Projects/flashIO/js-test/mbed-js-example/node_modules/gulp-run/command.js:166:13)
    at ChildProcess.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

```

**Comment by janjongboom** [comment]
@peterwilli Yes, this is fixed in https://github.com/jerryscript-project/jerryscript/pull/1988 but not upstreamed yet. 

To fix in the meantime, open `build/jerryscript/.mbedignore` and add:

```
jerry-libm/*
```

to the file.

**Comment by janjongboom** [comment]
Also note that this project will not link on nRF51-DK because the target does not have enough flash available. It does work on nRF52-DK.

**Comment by peterwilli** [comment]
Thanks, will try now

**Comment by peterwilli** [comment]
@janjongboom Wow cool, you in NL too? 👍 
My board is nRF52840 preview developer kit. Not sure if that fits the profile on nRF52-DK but I assume it will.

**Comment by peterwilli** [comment]
@janjongboom my development board has 1MB flash (see: http://eu.mouser.com/pdfdocs/Nordic_nRF52840_Specifications.pdf)

I can't sucessfully copy my `mbedos5.hex` to my board right now, and I think it's because of the 1.3MB file size it currently has. But not sure yet, since the .hex file is not binary but text based. Can you shed some light on that? Thanks!

**Comment by janjongboom** [comment]
@peterwilli Yeah, compiling for nRF52-DK target should be fine. Regarding the copying, see #3, putting the JLINK bootloader on your board should work.

**Comment by peterwilli** [comment]
@janjongboom I tried copying with another laptop on the JLINK Drive and it worked. I think it's because I tried copying from a chromebook initially, appearantly it copies in a different kind of way, not sure what happened, but copying on a regular linux computer worked out fine.

**Comment by janjongboom** [comment]
@peterwilli Great!
