### ISSUE TITLE
[ERROR] Attribute 'default_build' not found in target 'NRF52_DK' [mbed] ERROR: "python" returned error code 1.

### ISSUE THREAD

**Issue by pmcalabrese** [ARMmbed/mbed-js-example#5]
after run npm update i get this error.

```
cd jerryscript/targets/mbedos5 && pip install -r tools/requirements.txt && rm -f source/js_encoded.cpp && rm -f source/pins.cpp && rm -f source/main.cpp && make BOARD=NRF52_DK EXTRA_SRC="../../../source" EXTERN_BUILD_DIR=../../../out/NRF52_DK NO_JS=1
Requirement already satisfied: pycparser in /Users/mca/.virtualenvs/mbed/lib/python2.7/site-packages (from -r tools/requirements.txt (line 1))
Requirement already satisfied: simpleeval in /Users/mca/.virtualenvs/mbed/lib/python2.7/site-packages (from -r tools/requirements.txt (line 2))
Requirement already satisfied: pycparserext in /Users/mca/.virtualenvs/mbed/lib/python2.7/site-packages (from -r tools/requirements.txt (line 3))
Requirement already satisfied: ply>=3.4 in /Users/mca/.virtualenvs/mbed/lib/python2.7/site-packages (from pycparserext->-r tools/requirements.txt (line 3))
python tools/generate_pins.py NRF52_DK
mbed config root .
[mbed] . now set as default root in program "mbed-js-example"
mbed toolchain GCC_ARM
[mbed] GCC_ARM now set as default toolchain in program "mbed-js-example"
mbed target NRF52_DK
[mbed] NRF52_DK now set as default target in program "mbed-js-example"
mbed deploy
[mbed] Updating library "mbed-os" to rev #d5de476f74dd
mbed target NRF52_DK
[mbed] NRF52_DK now set as default target in program "mbed-js-example"
mbed compile -j0 --source . --source ../../ --source ../../../source --build ../../../out/NRF52_DK -D "CONFIG_MEM_HEAP_AREA_SIZE=(1024*16)" -t GCC_ARM
[ERROR] Attribute 'default_build' not found in target 'NRF52_DK'
[mbed] ERROR: "python" returned error code 1.
[mbed] ERROR: Command "python -u /Users/mca/dev/mbed-js-example/.temp/tools/make.py -t GCC_ARM -m NRF52_DK --source . --source ../../ --source ../../../source --build ../../../out/NRF52_DK -j0 -D CONFIG_MEM_HEAP_AREA_SIZE=(1024*16)" in "/Users/mca/dev/mbed-js-example/build/jerryscript/targets/mbedos5"
---
make[1]: *** [all] Error 1
make: *** [all] Error 2
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Command `make BOARD=NRF52_DK EXTRAS=` exited with code 2
    at ChildProcess.handleSubShellExit (/Users/mca/dev/mbed-js-example/node_modules/gulp-run/command.js:166:13)
    at ChildProcess.g (events.js:291:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

I believe the interesting line is `[ERROR] Attribute 'default_build' not found in target 'NRF52_DK'
[mbed] ERROR: "python" returned error code 1.`. What is the *default_build*? How can i fix it?

Thank you in advance! and wish you a great 2017 :)

**Comment by janjongboom** [comment]
See discussion in https://github.com/ARMmbed/mbed-js-example/issues/2
